# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:            
  build:
    working_directory: ~/console
    branches:
      only: 
        - /.*/

    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
        environment:
          POSTGRES_USER: root
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - run:
          name: Install dependencies
          command: |
              sudo apt-get update
              curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
              sudo apt-get install git-lfs
              git lfs install 
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      # build blockchian by build_chain.sh
      - run: 
            name: fisco-bcos
            command: |
              sudo apt install -y openssl curl
              curl -LO https://raw.githubusercontent.com/FISCO-BCOS/FISCO-BCOS/release-2.0.1/tools/build_chain.sh && chmod u+x build_chain.sh
              bash <(curl -s https://raw.githubusercontent.com/FISCO-BCOS/FISCO-BCOS/release-2.0.1/tools/ci/download_bin.sh) -b release-2.0.1
              echo "127.0.0.1:4 agency1 1,2,3" > ipconf
              ./build_chain.sh -e bin/fisco-bcos -f ipconf -p 30300,20200,8545
              cd nodes/127.0.0.1
              ./start_all.sh

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/console/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      # run integration test for sdk
      - run:
          name: console
          command: |
            cp nodes/127.0.0.1/sdk/* src/main/resources/
            gradle test